on:
 push:
 workflow_dispatch:
 schedule:
   - cron:  '0 */6 * * *'

jobs:
 scrape:
   runs-on: ubuntu-latest
   steps:
   # Step 1: Prepare the environment
   - name: Check out this repo
     uses: actions/checkout@v2
     with:
       fetch-depth: 0
   # Step 5
   - name: Commit and push if it changed
     run: |-
       git config user.name "Automated"
       git config user.email "actions@users.noreply.github.com"
       touch test.txt
       git pull
       git add -A
       timestamp=$(date -u)
       git commit -m "Latest data: ${timestamp}" || exit 0
       git push
